name: check

on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 26.1
          - 26.2
          - 26.3
        file:
          - flymake-aspell.el
          - flycheck-aspell.el
        ignore_warnings:
          - true
        include:
          - emacs_version: snapshot
            file: flymake-aspell.el
            ignore_warnings: false
          - emacs_version: snapshot
            file: flycheck-aspell.el
            ignore_warnings: false
    steps:
    - uses: actions/checkout@v2
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}
    - uses: leotaku/elisp-check@master
      with:
        file: ${{ matrix.file }}
        ignore_warnings: ${{ matrix.ignore_warnings }}
